server:
  port: ${SERVER_PORT:8092}

spring:
  application:
    name: enx-api-java

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never

enx:
  cognito:
    region: ${COGNITO_REGION:}
    user-pool-id: ${COGNITO_USER_POOL_ID:}
    client-id: ${COGNITO_CLIENT_ID:}
    chrome-client-id: ${COGNITO_CHROME_CLIENT_ID:}

logging:
  level:
    root: INFO
    com.wiloon.enx: INFO
