linters:
  enable:
    - gofmt
    - golint
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - misspell
    - unconvert
    - gosec

run:
  deadline: 5m
  tests: true
  skip-dirs:
    - vendor

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck

linters-settings:
  golint:
    min-confidence: 0.8
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 3
  misspell:
    locale: US
