version: '3'

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  # ===========================================
  # Service Management
  # ===========================================

  # Sync Service
  sync:start:
    desc: Start enx-sync using taskfile (usage - task sync:start [MODE=fg|bg] - default is fg)
    dir: enx-sync
    vars:
      MODE: '{{.MODE | default "fg"}}'
    cmds:
      - task run MODE={{.MODE}}

  data:start:fg:
    desc: Start enx-sync in foreground
    cmds:
      - |
        if pgrep -f "bin/server.*enx.db" > /dev/null; then
          echo "⚠️  sync-service is already running (PID: $(pgrep -f 'bin/server.*enx.db'))"
          exit 1
        fi
        echo "🚀 Starting enx-sync in foreground..."
        echo "   gRPC: localhost:50051"
        echo "   HTTP: localhost:8090"
        echo "   Press Ctrl+C to stop"
        echo ""
        cd enx-sync && ./bin/server --db=/var/lib/enx-api/enx.db

  sync:start:bg:
    desc: Start enx-sync in background
    cmds:
      - |
        if pgrep -f "bin/server.*enx.db" > /dev/null; then
          echo "⚠️  sync-service is already running"
          exit 1
        fi
        echo "🚀 Starting enx-sync..."
        cd enx-sync && ./bin/server --db=/var/lib/enx-api/enx.db > /tmp/enx-sync.log 2>&1 &
        sleep 2
        if pgrep -f "bin/server.*enx.db" > /dev/null; then
          echo "✅ sync-service started (PID: $(pgrep -f 'bin/server.*enx.db'))"
          echo "   Logs: /tmp/enx-sync.log"
          echo "   gRPC: localhost:50051"
          echo "   HTTP: localhost:8090"
        else
          echo "❌ Failed to start sync-service"
          tail -20 /tmp/enx-sync.log
          exit 1
        fi

  data:stop:
    desc: Stop enx-sync
    cmds:
      - |
        PID=$(pgrep -f "bin/server.*enx.db" || echo "")
        if [ -z "$PID" ]; then
          echo "⚠️  sync-service is not running"
        else
          echo "🛑 Stopping sync-service (PID: $PID)..."
          kill $PID
          sleep 1
          if pgrep -f "bin/server.*enx.db" > /dev/null; then
            echo "⚠️  Forcing stop..."
            kill -9 $PID
          fi
          echo "✅ sync-service stopped"
        fi

  data:restart:
    desc: Restart enx-sync
    cmds:
      - task: data:stop
      - sleep 1
      - task: data:start

  data:logs:
    desc: Show enx-sync logs
    cmds:
      - tail -f /tmp/enx-sync.log

  # API Service
  api:stop:
    desc: Stop enx-api (calls enx-api taskfile)
    dir: enx-api
    cmds:
      - task stop

  api:restart:
    desc: Restart enx-api (calls enx-api taskfile)
    dir: enx-api
    cmds:
      - task restart

  api:status:
    desc: Show enx-api status (calls enx-api taskfile)
    dir: enx-api
    cmds:
      - task status

  api:logs:
    desc: Show enx-api logs
    dir: enx-api
    cmds:
      - |
        if [ -f enx-api.log ]; then
          tail -f enx-api.log
        else
          echo "⚠️  No log file found (enx-api.log)"
        fi

  # All Services
  status:
    desc: Show status of all services
    cmds:
      - |
        echo "=== ENX Services Status ==="
        echo ""
        echo "📊 Sync Service:"
        if pgrep -f "bin/server.*enx.db" > /dev/null; then
          echo "   ✅ Running (PID: $(pgrep -f 'bin/server.*enx.db'))"
          echo "   🔗 gRPC: localhost:50051"
          echo "   🔗 HTTP: localhost:8090"
        else
          echo "   ❌ Not running"
        fi
        echo ""
        echo "📊 API Service:"
        if pgrep -f "enx-api/enx-api$" > /dev/null; then
          echo "   ✅ Running (PID: $(pgrep -f 'enx-api/enx-api$'))"
          echo "   🔗 HTTP: localhost:8080"
        else
          echo "   ❌ Not running"
        fi

  # ===========================================
  # Setup & Installation
  # ===========================================

  setup:
    desc: Setup all projects (install dependencies)
    cmds:
      - task: setup-api
      - task: setup-chrome
      - task: setup-ui

  setup-api:
    desc: Setup enx-api
    dir: enx-api
    cmds:
      - task: deps

  setup-chrome:
    desc: Setup enx-chrome
    dir: enx-chrome
    cmds:
      - task: setup

  setup-ui:
    desc: Setup enx-ui
    dir: enx-ui
    cmds:
      - pnpm install

  # ===========================================
  # Development
  # ===========================================

  api:start:
    desc: Start enx-api in development mode (usage - task api:start [MODE=fg|bg] - default is fg)
    dir: enx-api
    vars:
      MODE: '{{.MODE | default "fg"}}'
    cmds:
      - task dev MODE={{.MODE}}

  dev-chrome:
    desc: Start Chrome browser with extension (auto-reload)
    dir: enx-chrome
    cmds:
      - task dev-chrome URL={{.URL | default "https://www.infoq.com/"}}

  dev-ui:
    desc: Start enx-ui in development mode
    dir: enx-ui
    cmds:
      - pnpm dev

  stop-dev:
    desc: Stop all development services
    cmds:
      - echo "Stopping development services..."
      - pkill -f "air" || true
      - pkill -f "vite.*enx-chrome" || true
      - pkill -f "dev-chrome.mjs" || true
      - pkill -f "chromium.*playwright" || true
      - echo "✅ All services stopped"

  restart-dev:
    desc: Restart all development services (clean restart)
    cmds:
      - echo "🔄 Restarting ENX development environment..."
      - echo "🛑 Stopping all processes..."
      - pkill -9 -f "air.*enx-api" 2>/dev/null || true
      - pkill -9 -f "vite.*enx-chrome" 2>/dev/null || true
      - pkill -9 -f "dev-chrome.mjs" 2>/dev/null || true
      - pkill -9 -f "chromium.*playwright" 2>/dev/null || true
      - bash -c 'lsof -ti:5173 2>/dev/null | xargs kill -9 2>/dev/null' || true
      - bash -c 'lsof -ti:8090 2>/dev/null | xargs kill -9 2>/dev/null' || true
      - echo "⏳ Waiting for ports to be freed..."
      - sleep 3
      - echo "🚀 Starting development environment..."
      - task: dev-all

  dev-logs:
    desc: Show development logs (API and Chrome watch)
    cmds:
      - echo "=== ENX Development Logs ==="
      - echo ""
      - echo "--- API Log (enx-api/logs/dev.log) ---"
      - tail -n 20 enx-api/logs/dev.log || echo "No API logs yet"
      - echo ""
      - echo "--- Chrome Watch Log (enx-chrome/logs/watch.log) ---"
      - tail -n 20 enx-chrome/logs/watch.log || echo "No Chrome watch logs yet"
      - echo ""
      - echo "💡 Tip - Use 'tail -f enx-api/logs/dev.log' to follow logs in real-time"

  # ===========================================
  # Building
  # ===========================================

  build:
    desc: Build all projects
    cmds:
      - task: build-api
      - task: chrome:build
      - task: build-ui

  build-api:
    desc: Build enx-api
    dir: enx-api
    cmds:
      - task: build

  chrome:build:
    desc: Build enx-chrome extension
    dir: enx-chrome
    cmds:
      - pnpm run build

  build-ui:
    desc: Build enx-ui
    dir: enx-ui
    cmds:
      - pnpm build

  # ===========================================
  # Testing
  # ===========================================

  test:
    desc: Run unit tests for all projects (fast, no database)
    cmds:
      - task: test-unit-api
      - task: test-chrome
      - task: test-ui

  test-unit:
    desc: Run unit tests only (no database, fast)
    cmds:
      - task: test-unit-api
      - task: test-chrome
      - task: test-ui

  test-integration:
    desc: Run integration tests (requires database and config)
    cmds:
      - task: test-integration-api

  test-all:
    desc: Run all tests (unit + integration)
    cmds:
      - task: test-unit
      - task: test-integration

  test-unit-api:
    desc: Run enx-api unit tests (no database required)
    dir: enx-api
    cmds:
      - echo "Running unit tests (no database)..."
      - go test -short ./...

  test-integration-api:
    desc: Run enx-api integration tests (requires database and config)
    dir: enx-api
    cmds:
      - echo "Setting up integration test environment..."
      - |
        # Create test database if not exists
        if [ ! -f enx.db ]; then
          echo "Creating test database..."
          sqlite3 enx.db < enx.sql
        fi
      - |
        # Create test config if not exists
        if [ ! -f config.toml ]; then
          echo "Using test config..."
          cp config-e2e.toml config.toml
        fi
      - echo "Running integration tests..."
      - go test -tags=integration ./...

  test-api:
    desc: Run all enx-api tests (unit + integration)
    dir: enx-api
    cmds:
      - task: test-unit-api
      - task: test-integration-api

  test-chrome:
    desc: Run enx-chrome tests (unit tests)
    dir: enx-chrome
    cmds:
      - pnpm test

  test-chrome-e2e:
    desc: Run enx-chrome E2E tests
    dir: enx-chrome
    cmds:
      - task: test-e2e

  test-ui:
    desc: Run enx-ui tests
    dir: enx-ui
    cmds:
      - |
        if [ ! -d "node_modules" ]; then
          echo "⚠️  enx-ui: node_modules not found, skipping tests"
          echo "   Run 'task setup-ui' to install dependencies"
        else
          pnpm test
        fi

  test-coverage:
    desc: Run tests with coverage for all projects
    cmds:
      - task: test-coverage-api
      - task: test-coverage-chrome

  test-coverage-api:
    desc: Run enx-api tests with coverage
    dir: enx-api
    cmds:
      - go test -cover -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out -o coverage.html

  test-coverage-chrome:
    desc: Run enx-chrome tests with coverage
    dir: enx-chrome
    cmds:
      - pnpm test -- --coverage

  # ===========================================
  # Code Quality
  # ===========================================

  # ===========================================
  # Cleaning
  # ===========================================

  clean:
    desc: Clean all build artifacts and dependencies
    cmds:
      - task: clean-api
      - task: clean-chrome
      - task: clean-ui

  clean-api:
    desc: Clean enx-api build artifacts
    dir: enx-api
    cmds:
      - task: clean

  clean-chrome:
    desc: Clean enx-chrome build artifacts
    dir: enx-chrome
    cmds:
      - task: clean

  clean-ui:
    desc: Clean enx-ui build artifacts
    dir: enx-ui
    cmds:
      - rm -rf .next
      - rm -rf node_modules
      - rm -rf build

  # ===========================================
  # Packaging & Distribution
  # ===========================================

  pack-chrome:
    desc: Pack enx-chrome extension for distribution
    dir: enx-chrome
    cmds:
      - task: pack

  # ===========================================
  # CI/CD
  # ===========================================

  # ===========================================
  # Database
  # ===========================================

  migrate:
    desc: Run database migrations for enx-api
    dir: enx-api
    cmds:
      - task migrate

  # ===========================================
  # Mock API
  # ===========================================

  mock-api:
    desc: Start mock API server
    dir: mock-api
    cmds:
      - pnpm install
      - node server.js
