// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: data_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Word message aligned with migrated database schema
type Word struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                 // UUID v4
	English       string                 `protobuf:"bytes,2,opt,name=english,proto3" json:"english,omitempty"`                       // English word (required, unique)
	Chinese       string                 `protobuf:"bytes,3,opt,name=chinese,proto3" json:"chinese,omitempty"`                       // Chinese translation (optional)
	Pronunciation string                 `protobuf:"bytes,4,opt,name=pronunciation,proto3" json:"pronunciation,omitempty"`           // Pronunciation guide (optional)
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // Unix timestamp in milliseconds
	LoadCount     int32                  `protobuf:"varint,6,opt,name=load_count,json=loadCount,proto3" json:"load_count,omitempty"` // Usage counter
	UpdatedAt     int64                  `protobuf:"varint,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // Unix timestamp in milliseconds (required)
	DeletedAt     int64                  `protobuf:"varint,8,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"` // Soft delete timestamp (0 = not deleted)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Word) Reset() {
	*x = Word{}
	mi := &file_data_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Word) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Word) ProtoMessage() {}

func (x *Word) ProtoReflect() protoreflect.Message {
	mi := &file_data_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Word.ProtoReflect.Descriptor instead.
func (*Word) Descriptor() ([]byte, []int) {
	return file_data_service_proto_rawDescGZIP(), []int{0}
}

func (x *Word) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Word) GetEnglish() string {
	if x != nil {
		return x.English
	}
	return ""
}

func (x *Word) GetChinese() string {
	if x != nil {
		return x.Chinese
	}
	return ""
}

func (x *Word) GetPronunciation() string {
	if x != nil {
		return x.Pronunciation
	}
	return ""
}

func (x *Word) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Word) GetLoadCount() int32 {
	if x != nil {
		return x.LoadCount
	}
	return 0
}

func (x *Word) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Word) GetDeletedAt() int64 {
	if x != nil {
		return x.DeletedAt
	}
	return 0
}

type GetWordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWordRequest) Reset() {
	*x = GetWordRequest{}
	mi := &file_data_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWordRequest) ProtoMessage() {}

func (x *GetWordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_data_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWordRequest.ProtoReflect.Descriptor instead.
func (*GetWordRequest) Descriptor() ([]byte, []int) {
	return file_data_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetWordRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetWordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Word          *Word                  `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWordResponse) Reset() {
	*x = GetWordResponse{}
	mi := &file_data_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWordResponse) ProtoMessage() {}

func (x *GetWordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_data_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWordResponse.ProtoReflect.Descriptor instead.
func (*GetWordResponse) Descriptor() ([]byte, []int) {
	return file_data_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetWordResponse) GetWord() *Word {
	if x != nil {
		return x.Word
	}
	return nil
}

type CreateWordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	English       string                 `protobuf:"bytes,1,opt,name=english,proto3" json:"english,omitempty"`
	Chinese       string                 `protobuf:"bytes,2,opt,name=chinese,proto3" json:"chinese,omitempty"`
	Pronunciation string                 `protobuf:"bytes,3,opt,name=pronunciation,proto3" json:"pronunciation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWordRequest) Reset() {
	*x = CreateWordRequest{}
	mi := &file_data_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWordRequest) ProtoMessage() {}

func (x *CreateWordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_data_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWordRequest.ProtoReflect.Descriptor instead.
func (*CreateWordRequest) Descriptor() ([]byte, []int) {
	return file_data_service_proto_rawDescGZIP(), []int{3}
}

func (x *CreateWordRequest) GetEnglish() string {
	if x != nil {
		return x.English
	}
	return ""
}

func (x *CreateWordRequest) GetChinese() string {
	if x != nil {
		return x.Chinese
	}
	return ""
}

func (x *CreateWordRequest) GetPronunciation() string {
	if x != nil {
		return x.Pronunciation
	}
	return ""
}

type CreateWordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Word          *Word                  `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWordResponse) Reset() {
	*x = CreateWordResponse{}
	mi := &file_data_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWordResponse) ProtoMessage() {}

func (x *CreateWordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_data_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWordResponse.ProtoReflect.Descriptor instead.
func (*CreateWordResponse) Descriptor() ([]byte, []int) {
	return file_data_service_proto_rawDescGZIP(), []int{4}
}

func (x *CreateWordResponse) GetWord() *Word {
	if x != nil {
		return x.Word
	}
	return nil
}

type UpdateWordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Word          *Word                  `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWordRequest) Reset() {
	*x = UpdateWordRequest{}
	mi := &file_data_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWordRequest) ProtoMessage() {}

func (x *UpdateWordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_data_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWordRequest.ProtoReflect.Descriptor instead.
func (*UpdateWordRequest) Descriptor() ([]byte, []int) {
	return file_data_service_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateWordRequest) GetWord() *Word {
	if x != nil {
		return x.Word
	}
	return nil
}

type UpdateWordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Word          *Word                  `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWordResponse) Reset() {
	*x = UpdateWordResponse{}
	mi := &file_data_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWordResponse) ProtoMessage() {}

func (x *UpdateWordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_data_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWordResponse.ProtoReflect.Descriptor instead.
func (*UpdateWordResponse) Descriptor() ([]byte, []int) {
	return file_data_service_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateWordResponse) GetWord() *Word {
	if x != nil {
		return x.Word
	}
	return nil
}

type DeleteWordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWordRequest) Reset() {
	*x = DeleteWordRequest{}
	mi := &file_data_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWordRequest) ProtoMessage() {}

func (x *DeleteWordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_data_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWordRequest.ProtoReflect.Descriptor instead.
func (*DeleteWordRequest) Descriptor() ([]byte, []int) {
	return file_data_service_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteWordRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteWordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWordResponse) Reset() {
	*x = DeleteWordResponse{}
	mi := &file_data_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWordResponse) ProtoMessage() {}

func (x *DeleteWordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_data_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWordResponse.ProtoReflect.Descriptor instead.
func (*DeleteWordResponse) Descriptor() ([]byte, []int) {
	return file_data_service_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteWordResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListWordsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWordsRequest) Reset() {
	*x = ListWordsRequest{}
	mi := &file_data_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWordsRequest) ProtoMessage() {}

func (x *ListWordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_data_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWordsRequest.ProtoReflect.Descriptor instead.
func (*ListWordsRequest) Descriptor() ([]byte, []int) {
	return file_data_service_proto_rawDescGZIP(), []int{9}
}

func (x *ListWordsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListWordsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListWordsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Words         []*Word                `protobuf:"bytes,1,rep,name=words,proto3" json:"words,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWordsResponse) Reset() {
	*x = ListWordsResponse{}
	mi := &file_data_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWordsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWordsResponse) ProtoMessage() {}

func (x *ListWordsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_data_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWordsResponse.ProtoReflect.Descriptor instead.
func (*ListWordsResponse) Descriptor() ([]byte, []int) {
	return file_data_service_proto_rawDescGZIP(), []int{10}
}

func (x *ListWordsResponse) GetWords() []*Word {
	if x != nil {
		return x.Words
	}
	return nil
}

func (x *ListWordsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type SyncWordsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SinceTimestamp int64                  `protobuf:"varint,1,opt,name=since_timestamp,json=sinceTimestamp,proto3" json:"since_timestamp,omitempty"` // Unix timestamp in milliseconds
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SyncWordsRequest) Reset() {
	*x = SyncWordsRequest{}
	mi := &file_data_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncWordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncWordsRequest) ProtoMessage() {}

func (x *SyncWordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_data_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncWordsRequest.ProtoReflect.Descriptor instead.
func (*SyncWordsRequest) Descriptor() ([]byte, []int) {
	return file_data_service_proto_rawDescGZIP(), []int{11}
}

func (x *SyncWordsRequest) GetSinceTimestamp() int64 {
	if x != nil {
		return x.SinceTimestamp
	}
	return 0
}

type SyncWordsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Word          *Word                  `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncWordsResponse) Reset() {
	*x = SyncWordsResponse{}
	mi := &file_data_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncWordsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncWordsResponse) ProtoMessage() {}

func (x *SyncWordsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_data_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncWordsResponse.ProtoReflect.Descriptor instead.
func (*SyncWordsResponse) Descriptor() ([]byte, []int) {
	return file_data_service_proto_rawDescGZIP(), []int{12}
}

func (x *SyncWordsResponse) GetWord() *Word {
	if x != nil {
		return x.Word
	}
	return nil
}

type SyncUserDictsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SinceTimestamp int64                  `protobuf:"varint,1,opt,name=since_timestamp,json=sinceTimestamp,proto3" json:"since_timestamp,omitempty"` // Unix timestamp in milliseconds
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SyncUserDictsRequest) Reset() {
	*x = SyncUserDictsRequest{}
	mi := &file_data_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncUserDictsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncUserDictsRequest) ProtoMessage() {}

func (x *SyncUserDictsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_data_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncUserDictsRequest.ProtoReflect.Descriptor instead.
func (*SyncUserDictsRequest) Descriptor() ([]byte, []int) {
	return file_data_service_proto_rawDescGZIP(), []int{13}
}

func (x *SyncUserDictsRequest) GetSinceTimestamp() int64 {
	if x != nil {
		return x.SinceTimestamp
	}
	return 0
}

type SyncUserDictsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserDict      *UserDict              `protobuf:"bytes,1,opt,name=user_dict,json=userDict,proto3" json:"user_dict,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncUserDictsResponse) Reset() {
	*x = SyncUserDictsResponse{}
	mi := &file_data_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncUserDictsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncUserDictsResponse) ProtoMessage() {}

func (x *SyncUserDictsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_data_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncUserDictsResponse.ProtoReflect.Descriptor instead.
func (*SyncUserDictsResponse) Descriptor() ([]byte, []int) {
	return file_data_service_proto_rawDescGZIP(), []int{14}
}

func (x *SyncUserDictsResponse) GetUserDict() *UserDict {
	if x != nil {
		return x.UserDict
	}
	return nil
}

// UserDict message for user-specific word data
type UserDict struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UserId            string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                                   // User UUID
	WordId            string                 `protobuf:"bytes,2,opt,name=word_id,json=wordId,proto3" json:"word_id,omitempty"`                                   // Word UUID (foreign key to words.id)
	QueryCount        int32                  `protobuf:"varint,3,opt,name=query_count,json=queryCount,proto3" json:"query_count,omitempty"`                      // Number of times user queried this word
	AlreadyAcquainted int32                  `protobuf:"varint,4,opt,name=already_acquainted,json=alreadyAcquainted,proto3" json:"already_acquainted,omitempty"` // 0 = learning, 1 = already knows
	CreatedAt         int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                         // Unix timestamp in milliseconds
	UpdatedAt         int64                  `protobuf:"varint,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`                         // Unix timestamp in milliseconds
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UserDict) Reset() {
	*x = UserDict{}
	mi := &file_data_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDict) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDict) ProtoMessage() {}

func (x *UserDict) ProtoReflect() protoreflect.Message {
	mi := &file_data_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDict.ProtoReflect.Descriptor instead.
func (*UserDict) Descriptor() ([]byte, []int) {
	return file_data_service_proto_rawDescGZIP(), []int{15}
}

func (x *UserDict) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserDict) GetWordId() string {
	if x != nil {
		return x.WordId
	}
	return ""
}

func (x *UserDict) GetQueryCount() int32 {
	if x != nil {
		return x.QueryCount
	}
	return 0
}

func (x *UserDict) GetAlreadyAcquainted() int32 {
	if x != nil {
		return x.AlreadyAcquainted
	}
	return 0
}

func (x *UserDict) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *UserDict) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type GetUserDictRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	WordId        string                 `protobuf:"bytes,2,opt,name=word_id,json=wordId,proto3" json:"word_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserDictRequest) Reset() {
	*x = GetUserDictRequest{}
	mi := &file_data_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserDictRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserDictRequest) ProtoMessage() {}

func (x *GetUserDictRequest) ProtoReflect() protoreflect.Message {
	mi := &file_data_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserDictRequest.ProtoReflect.Descriptor instead.
func (*GetUserDictRequest) Descriptor() ([]byte, []int) {
	return file_data_service_proto_rawDescGZIP(), []int{16}
}

func (x *GetUserDictRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserDictRequest) GetWordId() string {
	if x != nil {
		return x.WordId
	}
	return ""
}

type GetUserDictResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserDict      *UserDict              `protobuf:"bytes,1,opt,name=user_dict,json=userDict,proto3" json:"user_dict,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserDictResponse) Reset() {
	*x = GetUserDictResponse{}
	mi := &file_data_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserDictResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserDictResponse) ProtoMessage() {}

func (x *GetUserDictResponse) ProtoReflect() protoreflect.Message {
	mi := &file_data_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserDictResponse.ProtoReflect.Descriptor instead.
func (*GetUserDictResponse) Descriptor() ([]byte, []int) {
	return file_data_service_proto_rawDescGZIP(), []int{17}
}

func (x *GetUserDictResponse) GetUserDict() *UserDict {
	if x != nil {
		return x.UserDict
	}
	return nil
}

type UpsertUserDictRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserDict      *UserDict              `protobuf:"bytes,1,opt,name=user_dict,json=userDict,proto3" json:"user_dict,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertUserDictRequest) Reset() {
	*x = UpsertUserDictRequest{}
	mi := &file_data_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertUserDictRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertUserDictRequest) ProtoMessage() {}

func (x *UpsertUserDictRequest) ProtoReflect() protoreflect.Message {
	mi := &file_data_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertUserDictRequest.ProtoReflect.Descriptor instead.
func (*UpsertUserDictRequest) Descriptor() ([]byte, []int) {
	return file_data_service_proto_rawDescGZIP(), []int{18}
}

func (x *UpsertUserDictRequest) GetUserDict() *UserDict {
	if x != nil {
		return x.UserDict
	}
	return nil
}

type UpsertUserDictResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserDict      *UserDict              `protobuf:"bytes,1,opt,name=user_dict,json=userDict,proto3" json:"user_dict,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertUserDictResponse) Reset() {
	*x = UpsertUserDictResponse{}
	mi := &file_data_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertUserDictResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertUserDictResponse) ProtoMessage() {}

func (x *UpsertUserDictResponse) ProtoReflect() protoreflect.Message {
	mi := &file_data_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertUserDictResponse.ProtoReflect.Descriptor instead.
func (*UpsertUserDictResponse) Descriptor() ([]byte, []int) {
	return file_data_service_proto_rawDescGZIP(), []int{19}
}

func (x *UpsertUserDictResponse) GetUserDict() *UserDict {
	if x != nil {
		return x.UserDict
	}
	return nil
}

var File_data_service_proto protoreflect.FileDescriptor

const file_data_service_proto_rawDesc = "" +
	"\n" +
	"\x12data_service.proto\x12\venx.data.v1\"\xec\x01\n" +
	"\x04Word\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aenglish\x18\x02 \x01(\tR\aenglish\x12\x18\n" +
	"\achinese\x18\x03 \x01(\tR\achinese\x12$\n" +
	"\rpronunciation\x18\x04 \x01(\tR\rpronunciation\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"load_count\x18\x06 \x01(\x05R\tloadCount\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\x03R\tupdatedAt\x12\x1d\n" +
	"\n" +
	"deleted_at\x18\b \x01(\x03R\tdeletedAt\" \n" +
	"\x0eGetWordRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"8\n" +
	"\x0fGetWordResponse\x12%\n" +
	"\x04word\x18\x01 \x01(\v2\x11.enx.data.v1.WordR\x04word\"m\n" +
	"\x11CreateWordRequest\x12\x18\n" +
	"\aenglish\x18\x01 \x01(\tR\aenglish\x12\x18\n" +
	"\achinese\x18\x02 \x01(\tR\achinese\x12$\n" +
	"\rpronunciation\x18\x03 \x01(\tR\rpronunciation\";\n" +
	"\x12CreateWordResponse\x12%\n" +
	"\x04word\x18\x01 \x01(\v2\x11.enx.data.v1.WordR\x04word\":\n" +
	"\x11UpdateWordRequest\x12%\n" +
	"\x04word\x18\x01 \x01(\v2\x11.enx.data.v1.WordR\x04word\";\n" +
	"\x12UpdateWordResponse\x12%\n" +
	"\x04word\x18\x01 \x01(\v2\x11.enx.data.v1.WordR\x04word\"#\n" +
	"\x11DeleteWordRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"$\n" +
	"\x12DeleteWordResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"@\n" +
	"\x10ListWordsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"R\n" +
	"\x11ListWordsResponse\x12'\n" +
	"\x05words\x18\x01 \x03(\v2\x11.enx.data.v1.WordR\x05words\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\";\n" +
	"\x10SyncWordsRequest\x12'\n" +
	"\x0fsince_timestamp\x18\x01 \x01(\x03R\x0esinceTimestamp\":\n" +
	"\x11SyncWordsResponse\x12%\n" +
	"\x04word\x18\x01 \x01(\v2\x11.enx.data.v1.WordR\x04word\"?\n" +
	"\x14SyncUserDictsRequest\x12'\n" +
	"\x0fsince_timestamp\x18\x01 \x01(\x03R\x0esinceTimestamp\"K\n" +
	"\x15SyncUserDictsResponse\x122\n" +
	"\tuser_dict\x18\x01 \x01(\v2\x15.enx.data.v1.UserDictR\buserDict\"\xca\x01\n" +
	"\bUserDict\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\aword_id\x18\x02 \x01(\tR\x06wordId\x12\x1f\n" +
	"\vquery_count\x18\x03 \x01(\x05R\n" +
	"queryCount\x12-\n" +
	"\x12already_acquainted\x18\x04 \x01(\x05R\x11alreadyAcquainted\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\x03R\tupdatedAt\"F\n" +
	"\x12GetUserDictRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\aword_id\x18\x02 \x01(\tR\x06wordId\"I\n" +
	"\x13GetUserDictResponse\x122\n" +
	"\tuser_dict\x18\x01 \x01(\v2\x15.enx.data.v1.UserDictR\buserDict\"K\n" +
	"\x15UpsertUserDictRequest\x122\n" +
	"\tuser_dict\x18\x01 \x01(\v2\x15.enx.data.v1.UserDictR\buserDict\"L\n" +
	"\x16UpsertUserDictResponse\x122\n" +
	"\tuser_dict\x18\x01 \x01(\v2\x15.enx.data.v1.UserDictR\buserDict2\xe1\x05\n" +
	"\vDataService\x12D\n" +
	"\aGetWord\x12\x1b.enx.data.v1.GetWordRequest\x1a\x1c.enx.data.v1.GetWordResponse\x12M\n" +
	"\n" +
	"CreateWord\x12\x1e.enx.data.v1.CreateWordRequest\x1a\x1f.enx.data.v1.CreateWordResponse\x12M\n" +
	"\n" +
	"UpdateWord\x12\x1e.enx.data.v1.UpdateWordRequest\x1a\x1f.enx.data.v1.UpdateWordResponse\x12M\n" +
	"\n" +
	"DeleteWord\x12\x1e.enx.data.v1.DeleteWordRequest\x1a\x1f.enx.data.v1.DeleteWordResponse\x12J\n" +
	"\tListWords\x12\x1d.enx.data.v1.ListWordsRequest\x1a\x1e.enx.data.v1.ListWordsResponse\x12P\n" +
	"\vGetUserDict\x12\x1f.enx.data.v1.GetUserDictRequest\x1a .enx.data.v1.GetUserDictResponse\x12Y\n" +
	"\x0eUpsertUserDict\x12\".enx.data.v1.UpsertUserDictRequest\x1a#.enx.data.v1.UpsertUserDictResponse\x12L\n" +
	"\tSyncWords\x12\x1d.enx.data.v1.SyncWordsRequest\x1a\x1e.enx.data.v1.SyncWordsResponse0\x01\x12X\n" +
	"\rSyncUserDicts\x12!.enx.data.v1.SyncUserDictsRequest\x1a\".enx.data.v1.SyncUserDictsResponse0\x01B\vZ\tenx/protob\x06proto3"

var (
	file_data_service_proto_rawDescOnce sync.Once
	file_data_service_proto_rawDescData []byte
)

func file_data_service_proto_rawDescGZIP() []byte {
	file_data_service_proto_rawDescOnce.Do(func() {
		file_data_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_data_service_proto_rawDesc), len(file_data_service_proto_rawDesc)))
	})
	return file_data_service_proto_rawDescData
}

var file_data_service_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_data_service_proto_goTypes = []any{
	(*Word)(nil),                   // 0: enx.data.v1.Word
	(*GetWordRequest)(nil),         // 1: enx.data.v1.GetWordRequest
	(*GetWordResponse)(nil),        // 2: enx.data.v1.GetWordResponse
	(*CreateWordRequest)(nil),      // 3: enx.data.v1.CreateWordRequest
	(*CreateWordResponse)(nil),     // 4: enx.data.v1.CreateWordResponse
	(*UpdateWordRequest)(nil),      // 5: enx.data.v1.UpdateWordRequest
	(*UpdateWordResponse)(nil),     // 6: enx.data.v1.UpdateWordResponse
	(*DeleteWordRequest)(nil),      // 7: enx.data.v1.DeleteWordRequest
	(*DeleteWordResponse)(nil),     // 8: enx.data.v1.DeleteWordResponse
	(*ListWordsRequest)(nil),       // 9: enx.data.v1.ListWordsRequest
	(*ListWordsResponse)(nil),      // 10: enx.data.v1.ListWordsResponse
	(*SyncWordsRequest)(nil),       // 11: enx.data.v1.SyncWordsRequest
	(*SyncWordsResponse)(nil),      // 12: enx.data.v1.SyncWordsResponse
	(*SyncUserDictsRequest)(nil),   // 13: enx.data.v1.SyncUserDictsRequest
	(*SyncUserDictsResponse)(nil),  // 14: enx.data.v1.SyncUserDictsResponse
	(*UserDict)(nil),               // 15: enx.data.v1.UserDict
	(*GetUserDictRequest)(nil),     // 16: enx.data.v1.GetUserDictRequest
	(*GetUserDictResponse)(nil),    // 17: enx.data.v1.GetUserDictResponse
	(*UpsertUserDictRequest)(nil),  // 18: enx.data.v1.UpsertUserDictRequest
	(*UpsertUserDictResponse)(nil), // 19: enx.data.v1.UpsertUserDictResponse
}
var file_data_service_proto_depIdxs = []int32{
	0,  // 0: enx.data.v1.GetWordResponse.word:type_name -> enx.data.v1.Word
	0,  // 1: enx.data.v1.CreateWordResponse.word:type_name -> enx.data.v1.Word
	0,  // 2: enx.data.v1.UpdateWordRequest.word:type_name -> enx.data.v1.Word
	0,  // 3: enx.data.v1.UpdateWordResponse.word:type_name -> enx.data.v1.Word
	0,  // 4: enx.data.v1.ListWordsResponse.words:type_name -> enx.data.v1.Word
	0,  // 5: enx.data.v1.SyncWordsResponse.word:type_name -> enx.data.v1.Word
	15, // 6: enx.data.v1.SyncUserDictsResponse.user_dict:type_name -> enx.data.v1.UserDict
	15, // 7: enx.data.v1.GetUserDictResponse.user_dict:type_name -> enx.data.v1.UserDict
	15, // 8: enx.data.v1.UpsertUserDictRequest.user_dict:type_name -> enx.data.v1.UserDict
	15, // 9: enx.data.v1.UpsertUserDictResponse.user_dict:type_name -> enx.data.v1.UserDict
	1,  // 10: enx.data.v1.DataService.GetWord:input_type -> enx.data.v1.GetWordRequest
	3,  // 11: enx.data.v1.DataService.CreateWord:input_type -> enx.data.v1.CreateWordRequest
	5,  // 12: enx.data.v1.DataService.UpdateWord:input_type -> enx.data.v1.UpdateWordRequest
	7,  // 13: enx.data.v1.DataService.DeleteWord:input_type -> enx.data.v1.DeleteWordRequest
	9,  // 14: enx.data.v1.DataService.ListWords:input_type -> enx.data.v1.ListWordsRequest
	16, // 15: enx.data.v1.DataService.GetUserDict:input_type -> enx.data.v1.GetUserDictRequest
	18, // 16: enx.data.v1.DataService.UpsertUserDict:input_type -> enx.data.v1.UpsertUserDictRequest
	11, // 17: enx.data.v1.DataService.SyncWords:input_type -> enx.data.v1.SyncWordsRequest
	13, // 18: enx.data.v1.DataService.SyncUserDicts:input_type -> enx.data.v1.SyncUserDictsRequest
	2,  // 19: enx.data.v1.DataService.GetWord:output_type -> enx.data.v1.GetWordResponse
	4,  // 20: enx.data.v1.DataService.CreateWord:output_type -> enx.data.v1.CreateWordResponse
	6,  // 21: enx.data.v1.DataService.UpdateWord:output_type -> enx.data.v1.UpdateWordResponse
	8,  // 22: enx.data.v1.DataService.DeleteWord:output_type -> enx.data.v1.DeleteWordResponse
	10, // 23: enx.data.v1.DataService.ListWords:output_type -> enx.data.v1.ListWordsResponse
	17, // 24: enx.data.v1.DataService.GetUserDict:output_type -> enx.data.v1.GetUserDictResponse
	19, // 25: enx.data.v1.DataService.UpsertUserDict:output_type -> enx.data.v1.UpsertUserDictResponse
	12, // 26: enx.data.v1.DataService.SyncWords:output_type -> enx.data.v1.SyncWordsResponse
	14, // 27: enx.data.v1.DataService.SyncUserDicts:output_type -> enx.data.v1.SyncUserDictsResponse
	19, // [19:28] is the sub-list for method output_type
	10, // [10:19] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_data_service_proto_init() }
func file_data_service_proto_init() {
	if File_data_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_data_service_proto_rawDesc), len(file_data_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_data_service_proto_goTypes,
		DependencyIndexes: file_data_service_proto_depIdxs,
		MessageInfos:      file_data_service_proto_msgTypes,
	}.Build()
	File_data_service_proto = out.File
	file_data_service_proto_goTypes = nil
	file_data_service_proto_depIdxs = nil
}
