version: '3'

vars:
  EXT_NAME: enx-chrome-extension
  VERSION:
    sh: node -p "require('./package.json').version"

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  help:
    desc: Show available tasks (alias for default)
    cmds:
      - task --list

  install:
    desc: Install dependencies
    cmds:
      - echo "Installing dependencies for {{.EXT_NAME}}..."
      - pnpm install
      - echo "Dependencies installed successfully!"

  dev:
    desc: Start development server with hot reload
    cmds:
      - echo "Starting development server..."
      - pnpm run dev

  build:
    desc: Build extension for production
    cmds:
      - echo "Building {{.EXT_NAME}} v{{.VERSION}}..."
      - pnpm run build
      - echo "Build completed! Output in dist/"

  build-watch:
    desc: Build extension in watch mode
    cmds:
      - echo "Building in watch mode..."
      - pnpm run build -- --watch

  preview:
    desc: Preview production build
    cmds:
      - pnpm run preview

  test:
    desc: Run tests
    cmds:
      - echo "Running tests..."
      - pnpm test

  test-watch:
    desc: Run tests in watch mode
    cmds:
      - echo "Running tests in watch mode..."
      - pnpm run test:watch

  test-coverage:
    desc: Run tests with coverage
    cmds:
      - echo "Running tests with coverage..."
      - pnpm test -- --coverage

  test-e2e:
    desc: Run E2E tests with Playwright
    cmds:
      - echo "Running E2E tests..."
      - echo "⚠️  Make sure extension is built first (task build)"
      - pnpm run test:e2e

  test-e2e-ui:
    desc: Run E2E tests with Playwright UI
    cmds:
      - echo "Opening Playwright UI..."
      - echo "⚠️  Make sure extension is built first (task build)"
      - pnpm run test:e2e:ui

  test-e2e-debug:
    desc: Run E2E tests in debug mode
    cmds:
      - echo "Running E2E tests in debug mode..."
      - echo "⚠️  Make sure extension is built first (task build)"
      - pnpm run test:e2e:debug

  test-e2e-headed:
    desc: Run E2E tests with visible browser
    cmds:
      - echo "Running E2E tests with visible browser..."
      - echo "⚠️  Make sure extension is built first (task build)"
      - pnpm run test:e2e:headed

  test-all:
    desc: Run all tests (unit + E2E)
    cmds:
      - echo "Running all tests..."
      - task test
      - echo ""
      - task test-e2e
      - echo ""
      - echo "All tests completed!"

  lint:
    desc: Lint code
    cmds:
      - echo "Linting code..."
      - pnpm run lint

  lint-fix:
    desc: Fix linting issues
    cmds:
      - echo "Fixing linting issues..."
      - pnpm run lint:fix

  format:
    desc: Format code with Prettier
    cmds:
      - echo "Formatting code..."
      - pnpm run format

  format-check:
    desc: Check code formatting
    cmds:
      - echo "Checking code formatting..."
      - pnpm run format:check

  clean:
    desc: Clean build artifacts and dependencies
    cmds:
      - echo "Cleaning build artifacts..."
      - rm -rf dist
      - rm -rf node_modules
      - echo "Clean completed!"

  clean-dist:
    desc: Clean only build output
    cmds:
      - echo "Cleaning dist directory..."
      - rm -rf dist
      - echo "Dist cleaned!"

  check:
    desc: Run all checks (lint, format-check, test)
    cmds:
      - task lint
      - task format-check
      - task test
      - echo "All checks passed!"

  pack:
    desc: Build and create zip for Chrome Web Store
    deps:
      - build
    cmds:
      - echo "Creating extension package..."
      - cd dist && zip -r ../{{.EXT_NAME}}-v{{.VERSION}}.zip .
      - echo "Package created {{.EXT_NAME}}-v{{.VERSION}}.zip"

  version:
    desc: Show extension version
    cmds:
      - echo "Extension {{.EXT_NAME}}"
      - echo "Version {{.VERSION}}"

  deps-update:
    desc: Update dependencies
    cmds:
      - echo "Checking for outdated dependencies..."
      - pnpm outdated || true
      - echo ""
      - echo "To update, run pnpm update"

  deps-audit:
    desc: Check for security vulnerabilities
    cmds:
      - echo "Auditing dependencies..."
      - pnpm audit

  deps-audit-fix:
    desc: Fix security vulnerabilities
    cmds:
      - echo "Fixing vulnerabilities..."
      - pnpm audit --fix

  setup:
    desc: Complete setup (install + build)
    cmds:
      - task install
      - task build
      - echo ""
      - echo "Setup complete! Extension is ready."
      - echo "Load the 'dist' directory in Chrome as an unpacked extension."

  reload:
    desc: Rebuild and remind to reload extension
    deps:
      - build
    cmds:
      - echo ""
      - echo "Build complete! Remember to:"
      - echo "1. Go to chrome://extensions"
      - echo "2. Click the reload button on {{.EXT_NAME}}"

  ci:
    desc: CI/CD workflow (install, lint, test, build)
    cmds:
      - task install
      - task lint
      - task test
      - task build
      - echo "CI workflow completed successfully!"

  open-chrome:
    desc: Open Chrome extensions page
    cmds:
      - echo "Opening Chrome extensions page..."
      - open -a "Google Chrome" "chrome://extensions"

  info:
    desc: Show project information
    cmds:
      - echo "Project {{.EXT_NAME}}"
      - echo "Version {{.VERSION}}"
      - echo ""
      - echo "Quick commands"
      - echo "  task dev      - Start development server"
      - echo "  task build    - Build for production"
      - echo "  task test     - Run tests"
      - echo "  task pack     - Create distributable zip"
      - echo ""
      - echo "For all commands, run task --list"
