// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/data_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Word struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	English        string                 `protobuf:"bytes,2,opt,name=english,proto3" json:"english,omitempty"`
	Chinese        string                 `protobuf:"bytes,3,opt,name=chinese,proto3" json:"chinese,omitempty"`
	Phonetic       string                 `protobuf:"bytes,4,opt,name=phonetic,proto3" json:"phonetic,omitempty"`
	Definition     string                 `protobuf:"bytes,5,opt,name=definition,proto3" json:"definition,omitempty"`
	UpdateDatetime string                 `protobuf:"bytes,6,opt,name=update_datetime,json=updateDatetime,proto3" json:"update_datetime,omitempty"`
	IsDeleted      bool                   `protobuf:"varint,7,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Word) Reset() {
	*x = Word{}
	mi := &file_proto_data_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Word) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Word) ProtoMessage() {}

func (x *Word) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Word.ProtoReflect.Descriptor instead.
func (*Word) Descriptor() ([]byte, []int) {
	return file_proto_data_service_proto_rawDescGZIP(), []int{0}
}

func (x *Word) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Word) GetEnglish() string {
	if x != nil {
		return x.English
	}
	return ""
}

func (x *Word) GetChinese() string {
	if x != nil {
		return x.Chinese
	}
	return ""
}

func (x *Word) GetPhonetic() string {
	if x != nil {
		return x.Phonetic
	}
	return ""
}

func (x *Word) GetDefinition() string {
	if x != nil {
		return x.Definition
	}
	return ""
}

func (x *Word) GetUpdateDatetime() string {
	if x != nil {
		return x.UpdateDatetime
	}
	return ""
}

func (x *Word) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

type GetWordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWordRequest) Reset() {
	*x = GetWordRequest{}
	mi := &file_proto_data_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWordRequest) ProtoMessage() {}

func (x *GetWordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWordRequest.ProtoReflect.Descriptor instead.
func (*GetWordRequest) Descriptor() ([]byte, []int) {
	return file_proto_data_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetWordRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetWordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Word          *Word                  `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWordResponse) Reset() {
	*x = GetWordResponse{}
	mi := &file_proto_data_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWordResponse) ProtoMessage() {}

func (x *GetWordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWordResponse.ProtoReflect.Descriptor instead.
func (*GetWordResponse) Descriptor() ([]byte, []int) {
	return file_proto_data_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetWordResponse) GetWord() *Word {
	if x != nil {
		return x.Word
	}
	return nil
}

type CreateWordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	English       string                 `protobuf:"bytes,1,opt,name=english,proto3" json:"english,omitempty"`
	Chinese       string                 `protobuf:"bytes,2,opt,name=chinese,proto3" json:"chinese,omitempty"`
	Phonetic      string                 `protobuf:"bytes,3,opt,name=phonetic,proto3" json:"phonetic,omitempty"`
	Definition    string                 `protobuf:"bytes,4,opt,name=definition,proto3" json:"definition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWordRequest) Reset() {
	*x = CreateWordRequest{}
	mi := &file_proto_data_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWordRequest) ProtoMessage() {}

func (x *CreateWordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWordRequest.ProtoReflect.Descriptor instead.
func (*CreateWordRequest) Descriptor() ([]byte, []int) {
	return file_proto_data_service_proto_rawDescGZIP(), []int{3}
}

func (x *CreateWordRequest) GetEnglish() string {
	if x != nil {
		return x.English
	}
	return ""
}

func (x *CreateWordRequest) GetChinese() string {
	if x != nil {
		return x.Chinese
	}
	return ""
}

func (x *CreateWordRequest) GetPhonetic() string {
	if x != nil {
		return x.Phonetic
	}
	return ""
}

func (x *CreateWordRequest) GetDefinition() string {
	if x != nil {
		return x.Definition
	}
	return ""
}

type CreateWordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Word          *Word                  `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWordResponse) Reset() {
	*x = CreateWordResponse{}
	mi := &file_proto_data_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWordResponse) ProtoMessage() {}

func (x *CreateWordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWordResponse.ProtoReflect.Descriptor instead.
func (*CreateWordResponse) Descriptor() ([]byte, []int) {
	return file_proto_data_service_proto_rawDescGZIP(), []int{4}
}

func (x *CreateWordResponse) GetWord() *Word {
	if x != nil {
		return x.Word
	}
	return nil
}

type UpdateWordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Word          *Word                  `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWordRequest) Reset() {
	*x = UpdateWordRequest{}
	mi := &file_proto_data_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWordRequest) ProtoMessage() {}

func (x *UpdateWordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWordRequest.ProtoReflect.Descriptor instead.
func (*UpdateWordRequest) Descriptor() ([]byte, []int) {
	return file_proto_data_service_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateWordRequest) GetWord() *Word {
	if x != nil {
		return x.Word
	}
	return nil
}

type UpdateWordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Word          *Word                  `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWordResponse) Reset() {
	*x = UpdateWordResponse{}
	mi := &file_proto_data_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWordResponse) ProtoMessage() {}

func (x *UpdateWordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWordResponse.ProtoReflect.Descriptor instead.
func (*UpdateWordResponse) Descriptor() ([]byte, []int) {
	return file_proto_data_service_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateWordResponse) GetWord() *Word {
	if x != nil {
		return x.Word
	}
	return nil
}

type DeleteWordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWordRequest) Reset() {
	*x = DeleteWordRequest{}
	mi := &file_proto_data_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWordRequest) ProtoMessage() {}

func (x *DeleteWordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWordRequest.ProtoReflect.Descriptor instead.
func (*DeleteWordRequest) Descriptor() ([]byte, []int) {
	return file_proto_data_service_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteWordRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteWordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWordResponse) Reset() {
	*x = DeleteWordResponse{}
	mi := &file_proto_data_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWordResponse) ProtoMessage() {}

func (x *DeleteWordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWordResponse.ProtoReflect.Descriptor instead.
func (*DeleteWordResponse) Descriptor() ([]byte, []int) {
	return file_proto_data_service_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteWordResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type SyncWordsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SinceDatetime string                 `protobuf:"bytes,1,opt,name=since_datetime,json=sinceDatetime,proto3" json:"since_datetime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncWordsRequest) Reset() {
	*x = SyncWordsRequest{}
	mi := &file_proto_data_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncWordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncWordsRequest) ProtoMessage() {}

func (x *SyncWordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncWordsRequest.ProtoReflect.Descriptor instead.
func (*SyncWordsRequest) Descriptor() ([]byte, []int) {
	return file_proto_data_service_proto_rawDescGZIP(), []int{9}
}

func (x *SyncWordsRequest) GetSinceDatetime() string {
	if x != nil {
		return x.SinceDatetime
	}
	return ""
}

type SyncWordsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Word          *Word                  `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncWordsResponse) Reset() {
	*x = SyncWordsResponse{}
	mi := &file_proto_data_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncWordsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncWordsResponse) ProtoMessage() {}

func (x *SyncWordsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncWordsResponse.ProtoReflect.Descriptor instead.
func (*SyncWordsResponse) Descriptor() ([]byte, []int) {
	return file_proto_data_service_proto_rawDescGZIP(), []int{10}
}

func (x *SyncWordsResponse) GetWord() *Word {
	if x != nil {
		return x.Word
	}
	return nil
}

var File_proto_data_service_proto protoreflect.FileDescriptor

const file_proto_data_service_proto_rawDesc = "" +
	"\n" +
	"\x18proto/data_service.proto\x12\venx.data.v1\"\xce\x01\n" +
	"\x04Word\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aenglish\x18\x02 \x01(\tR\aenglish\x12\x18\n" +
	"\achinese\x18\x03 \x01(\tR\achinese\x12\x1a\n" +
	"\bphonetic\x18\x04 \x01(\tR\bphonetic\x12\x1e\n" +
	"\n" +
	"definition\x18\x05 \x01(\tR\n" +
	"definition\x12'\n" +
	"\x0fupdate_datetime\x18\x06 \x01(\tR\x0eupdateDatetime\x12\x1d\n" +
	"\n" +
	"is_deleted\x18\a \x01(\bR\tisDeleted\" \n" +
	"\x0eGetWordRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"8\n" +
	"\x0fGetWordResponse\x12%\n" +
	"\x04word\x18\x01 \x01(\v2\x11.enx.data.v1.WordR\x04word\"\x83\x01\n" +
	"\x11CreateWordRequest\x12\x18\n" +
	"\aenglish\x18\x01 \x01(\tR\aenglish\x12\x18\n" +
	"\achinese\x18\x02 \x01(\tR\achinese\x12\x1a\n" +
	"\bphonetic\x18\x03 \x01(\tR\bphonetic\x12\x1e\n" +
	"\n" +
	"definition\x18\x04 \x01(\tR\n" +
	"definition\";\n" +
	"\x12CreateWordResponse\x12%\n" +
	"\x04word\x18\x01 \x01(\v2\x11.enx.data.v1.WordR\x04word\":\n" +
	"\x11UpdateWordRequest\x12%\n" +
	"\x04word\x18\x01 \x01(\v2\x11.enx.data.v1.WordR\x04word\";\n" +
	"\x12UpdateWordResponse\x12%\n" +
	"\x04word\x18\x01 \x01(\v2\x11.enx.data.v1.WordR\x04word\"#\n" +
	"\x11DeleteWordRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"$\n" +
	"\x12DeleteWordResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"9\n" +
	"\x10SyncWordsRequest\x12%\n" +
	"\x0esince_datetime\x18\x01 \x01(\tR\rsinceDatetime\":\n" +
	"\x11SyncWordsResponse\x12%\n" +
	"\x04word\x18\x01 \x01(\v2\x11.enx.data.v1.WordR\x04word2\x8e\x03\n" +
	"\vDataService\x12D\n" +
	"\aGetWord\x12\x1b.enx.data.v1.GetWordRequest\x1a\x1c.enx.data.v1.GetWordResponse\x12M\n" +
	"\n" +
	"CreateWord\x12\x1e.enx.data.v1.CreateWordRequest\x1a\x1f.enx.data.v1.CreateWordResponse\x12M\n" +
	"\n" +
	"UpdateWord\x12\x1e.enx.data.v1.UpdateWordRequest\x1a\x1f.enx.data.v1.UpdateWordResponse\x12M\n" +
	"\n" +
	"DeleteWord\x12\x1e.enx.data.v1.DeleteWordRequest\x1a\x1f.enx.data.v1.DeleteWordResponse\x12L\n" +
	"\tSyncWords\x12\x1d.enx.data.v1.SyncWordsRequest\x1a\x1e.enx.data.v1.SyncWordsResponse0\x01B\x18Z\x16enx-data-service/protob\x06proto3"

var (
	file_proto_data_service_proto_rawDescOnce sync.Once
	file_proto_data_service_proto_rawDescData []byte
)

func file_proto_data_service_proto_rawDescGZIP() []byte {
	file_proto_data_service_proto_rawDescOnce.Do(func() {
		file_proto_data_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_data_service_proto_rawDesc), len(file_proto_data_service_proto_rawDesc)))
	})
	return file_proto_data_service_proto_rawDescData
}

var file_proto_data_service_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_data_service_proto_goTypes = []any{
	(*Word)(nil),               // 0: enx.data.v1.Word
	(*GetWordRequest)(nil),     // 1: enx.data.v1.GetWordRequest
	(*GetWordResponse)(nil),    // 2: enx.data.v1.GetWordResponse
	(*CreateWordRequest)(nil),  // 3: enx.data.v1.CreateWordRequest
	(*CreateWordResponse)(nil), // 4: enx.data.v1.CreateWordResponse
	(*UpdateWordRequest)(nil),  // 5: enx.data.v1.UpdateWordRequest
	(*UpdateWordResponse)(nil), // 6: enx.data.v1.UpdateWordResponse
	(*DeleteWordRequest)(nil),  // 7: enx.data.v1.DeleteWordRequest
	(*DeleteWordResponse)(nil), // 8: enx.data.v1.DeleteWordResponse
	(*SyncWordsRequest)(nil),   // 9: enx.data.v1.SyncWordsRequest
	(*SyncWordsResponse)(nil),  // 10: enx.data.v1.SyncWordsResponse
}
var file_proto_data_service_proto_depIdxs = []int32{
	0,  // 0: enx.data.v1.GetWordResponse.word:type_name -> enx.data.v1.Word
	0,  // 1: enx.data.v1.CreateWordResponse.word:type_name -> enx.data.v1.Word
	0,  // 2: enx.data.v1.UpdateWordRequest.word:type_name -> enx.data.v1.Word
	0,  // 3: enx.data.v1.UpdateWordResponse.word:type_name -> enx.data.v1.Word
	0,  // 4: enx.data.v1.SyncWordsResponse.word:type_name -> enx.data.v1.Word
	1,  // 5: enx.data.v1.DataService.GetWord:input_type -> enx.data.v1.GetWordRequest
	3,  // 6: enx.data.v1.DataService.CreateWord:input_type -> enx.data.v1.CreateWordRequest
	5,  // 7: enx.data.v1.DataService.UpdateWord:input_type -> enx.data.v1.UpdateWordRequest
	7,  // 8: enx.data.v1.DataService.DeleteWord:input_type -> enx.data.v1.DeleteWordRequest
	9,  // 9: enx.data.v1.DataService.SyncWords:input_type -> enx.data.v1.SyncWordsRequest
	2,  // 10: enx.data.v1.DataService.GetWord:output_type -> enx.data.v1.GetWordResponse
	4,  // 11: enx.data.v1.DataService.CreateWord:output_type -> enx.data.v1.CreateWordResponse
	6,  // 12: enx.data.v1.DataService.UpdateWord:output_type -> enx.data.v1.UpdateWordResponse
	8,  // 13: enx.data.v1.DataService.DeleteWord:output_type -> enx.data.v1.DeleteWordResponse
	10, // 14: enx.data.v1.DataService.SyncWords:output_type -> enx.data.v1.SyncWordsResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_data_service_proto_init() }
func file_proto_data_service_proto_init() {
	if File_proto_data_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_data_service_proto_rawDesc), len(file_proto_data_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_data_service_proto_goTypes,
		DependencyIndexes: file_proto_data_service_proto_depIdxs,
		MessageInfos:      file_proto_data_service_proto_msgTypes,
	}.Build()
	File_proto_data_service_proto = out.File
	file_proto_data_service_proto_goTypes = nil
	file_proto_data_service_proto_depIdxs = nil
}
