version: '3'

tasks:
  default:
    desc: List all available tasks
    cmds:
      - task --list

  proto:gen:
    desc: Generate gRPC protobuf code
    cmds:
      - protoc --go_out=proto --go_opt=paths=source_relative --go-grpc_out=proto --go-grpc_opt=paths=source_relative --proto_path=proto proto/data_service.proto
    sources:
      - proto/*.proto
    generates:
      - proto/*.pb.go

  proto:clean:
    desc: Clean generated proto files
    cmds:
      - rm -f proto/*.pb.go

  build:
    desc: Build the server binary
    cmds:
      - go build -o bin/server cmd/server/main.go

  run:
    desc: Run the server (builds if needed)
    vars:
      MODE: '{{.MODE | default "fg"}}'
      DB_PATH: '{{.DB_PATH | default "/var/lib/enx-api/enx.db"}}'
    cmds:
      - task: build
      - |
        if [ "{{.MODE}}" = "bg" ]; then
          ./bin/server --db={{.DB_PATH}} > /tmp/enx-data-service.log 2>&1 &
          echo "✅ Started in background (logs: /tmp/enx-data-service.log)"
        else
          ./bin/server --db={{.DB_PATH}}
        fi

  clean:
    desc: Clean up build artifacts
    cmds:
      - rm -rf bin/
